module.exports = [
  {
    "account": "hashquark.test",
    "name": "Hashquark",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "US",
    "fees_lower": 0,
    "fees_upper": 0,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 800000000000,
    "deposit_min": 10000000,
    "validator_power": 20000,
  },
  {
    "account": "figmentnetworks.test",
    "name": "Figment Networks",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "CA",
    "fees_lower": 80000,
    "fees_upper": 100000,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 800000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "bisontrails.test",
    "name": "Bison Trails",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "US",
    "fees_lower": 0,
    "fees_upper": 0,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 1000000000000,
    "deposit_min": 10003500,
    "validator_power": 15000,
  },
  {
    "account": "buildkinks.test",
    "name": "Buildlinks",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "CN",
    "fees_lower": 0,
    "fees_upper": 0,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "sparkpool.test",
    "name": "Sparkpool",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "CN",
    "fees_lower": 0,
    "fees_upper": 0,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "staked.test",
    "name": "Staked",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "US",
    "fees_lower": 0,
    "fees_upper": 0,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "justmining.test",
    "name": "Just Mining",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "GB",
    "fees_lower": 10000,
    "fees_upper": 30000,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "infstones.test",
    "name": "InfStones",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "CN",
    "fees_lower": 5000,
    "fees_upper": 20000,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "stakecube.test",
    "name": "StakeCube",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "DE",
    "fees_lower": 10000,
    "fees_upper": 30000,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
  {
    "account": "everstake.test",
    "name": "Everstake",
    "logo": "",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat lacus, in feugiat dui pellentesque sit amet. Praesent at lectus accumsan, semper elit quis.",
    "about": "Delegate your stakes to the validator HashQuark to get rewards.HashQuark is deeply involved in the construction of the public blockchains, running supernodes and providing infrastructure and services.",
    "country": "UA",
    "fees_lower": 5000,
    "fees_upper": 20000,
    "earnings": 152300,
    "return": null,
    "total_seats": 100,
    "available_seats": 2,
    "my_stake": 1189358,
    "total_stake": 7000000000,
    "deposit_min": 5000000,
    "validator_power": 15000,
  },
];